"use client";
import {useState} from "react";
const API="http://localhost:8000";
const labels={confirmed:"Confirmée",pending:"En attente",cancelled:"Annulée",created:"Création",updated:"Modification"};
export default function Home(){
 const [token,setToken]=useState(""),[data,setData]=useState(null),[error,setError]=useState(""),[busy,setBusy]=useState(false),[tab,setTab]=useState("Vue d’ensemble"),[notice,setNotice]=useState(""),[last,setLast]=useState(null);
 async function request(path,body){const r=await fetch(API+path,{headers:{Authorization:"Bearer "+token,"Content-Type":"application/json"},...(body?{method:"POST",body:JSON.stringify(body)}:{})});const j=await r.json();if(!r.ok)throw Error(typeof j.detail==="string"?j.detail:JSON.stringify(j.detail));return j}
 async function run(fn){setBusy(true);setError("");setNotice("");try{await fn()}catch(e){setError(e.message)}finally{setBusy(false)}}
 async function refresh(){setData(await request("/workspace"))}
 function login(e){e.preventDefault();run(refresh)}
 function simulate(e){e.preventDefault();const f=new FormData(e.currentTarget);const kind=f.get("kind");const b=data.bookings.find(b=>b.id===f.get("booking"));const body={event_id:crypto.randomUUID(),kind,reservation_id:kind==="created"?crypto.randomUUID():b?.id,property_id:kind==="created"?f.get("property"):b?.property_id,arrival:f.get("arrival"),departure:f.get("departure"),guest:f.get("guest")||"Voyageur Demo"};run(async()=>{await request("/simulate",body);setLast(body);await refresh();setNotice("Événement appliqué. Notifications simulées uniquement.")})}
 if(!data)return <main className="login"><span className="eyebrow">CONCIERGERIE INTELLIGENTE</span><h1>Cléora<span>.</span></h1><p>Vos logements. Vos voyageurs.<br/>Une seule vue pour tout suivre.</p><form onSubmit={login}><label>Clé d’accès du propriétaire<input type="password" required value={token} onChange={e=>setToken(e.target.value)} autoComplete="off"/></label><button disabled={busy}>{busy?"Connexion…":"Ouvrir mon espace"}</button></form><p className="muted">Démonstrateur local · Clés AREZKI_TOKEN et SARAH_TOKEN du fichier .env · Données fictives</p>{error&&<p role="alert">{error}</p>}</main>;
 const nav=["Vue d’ensemble","Logements","Réservations","Messages","Simulateur","Journal"];
 return <div className="shell"><aside><h2>Cléora<span>.</span></h2><p className="muted">Votre conciergerie</p><nav>{nav.map(n=><button className={tab===n?"active":"nav"} key={n} onClick={()=>setTab(n)}>{n}</button>)}</nav><button className="nav" onClick={()=>{setData(null);setToken("");setLast(null)}} disabled={busy}>Déconnexion</button></aside><main><header><div><span className="eyebrow">ESPACE PROPRIÉTAIRE</span><h1>Bonjour {data.owner==="arezki"?"Arezki":"Sarah"}</h1></div><span className="badge">PMS simulé · Aucun envoi réel</span></header>
 {error&&<p className="error" role="alert">{error}</p>}{notice&&<p className="notice" role="status">{notice}</p>}
 {(tab==="Vue d’ensemble")&&<><section className="stats"><article><h2>{data.properties.length}</h2>Logements</article><article><h2>{data.bookings.filter(b=>b.status==="confirmed").length}</h2>Réservations confirmées</article><article><h2>{data.events.length}</h2>Événements simulés</article></section><section className="grid"><article><h2>Vos logements</h2>{data.properties.map(p=><div className="row" key={p.id}><strong>{p.name}</strong><p className="muted">Fiche logement et consignes disponibles</p></div>)}</article><article><h2>Votre prochain test</h2><p>Créez un séjour, modifiez ses dates puis annulez-le. Suivez les notifications et les rappels dans le journal.</p><button onClick={()=>setTab("Simulateur")}>Ouvrir le simulateur</button></article></section></>}
 {tab==="Logements"&&<section className="grid">{data.properties.map(p=><article key={p.id}><h2>{p.name}</h2>{Object.entries(p.faq).map(([k,v])=><p key={k}><strong>{k} : </strong>{v}</p>)}</article>)}</section>}
 {tab==="Réservations"&&<article><h2>Réservations</h2><div className="table"><table><thead><tr><th>Voyageur</th><th>Logement</th><th>Arrivée</th><th>Départ</th><th>Statut</th></tr></thead><tbody>{data.bookings.map(b=><tr key={b.id}><td>{b.guest}</td><td>{data.properties.find(p=>p.id===b.property_id)?.name}</td><td>{b.arrival}</td><td>{b.departure}</td><td>{labels[b.status]}</td></tr>)}</tbody></table></div></article>}
 {tab==="Messages"&&<section className="grid"><article><h2>Simuler une question voyageur</h2><form onSubmit={e=>{e.preventDefault();const f=new FormData(e.currentTarget);run(async()=>{const r=await request("/bookings/"+f.get("booking")+"/question",{text:f.get("text")});await refresh();setNotice("Brouillon préparé ("+r.mode+"). Aucun message envoyé.")})}}><label>Réservation<select name="booking">{data.bookings.map(b=><option key={b.id} value={b.id}>{b.guest}</option>)}</select></label><label>Question<textarea name="text" required maxLength={2000} defaultValue="Où est le parking ?"/></label><button disabled={busy}>Préparer une réponse</button></form></article><article><h2>Conversations et brouillons</h2>{data.messages.map((m,i)=><div className="row" key={i}><small>{data.bookings.find(b=>b.id===m.reservation_id)?.guest} · {m.role==="guest"?"Voyageur":"Brouillon à valider"}</small><p>{m.text}</p></div>)}</article></section>}
 {tab==="Simulateur"&&<article><h2>Tester le cycle d’un séjour</h2><form onSubmit={simulate}><div className="grid"><label>Événement<select name="kind"><option value="created">Créer une réservation</option><option value="updated">Modifier les dates</option><option value="cancelled">Annuler une réservation</option></select></label><label>Logement pour une création<select name="property">{data.properties.map(p=><option key={p.id} value={p.id}>{p.name}</option>)}</select></label><label>Réservation à modifier / annuler<select name="booking">{data.bookings.filter(b=>b.status!=="cancelled").map(b=><option key={b.id} value={b.id}>{b.guest} · {b.arrival}</option>)}</select></label><label>Nouveau voyageur<input name="guest" defaultValue="Camille Demo" maxLength={100}/></label><label>Arrivée<input type="date" name="arrival" required/></label><label>Départ<input type="date" name="departure" required/></label></div><button disabled={busy}>Appliquer l’événement</button></form><p className="muted">Pour une annulation, les dates du séjour sont conservées. Les dates du formulaire doivent néanmoins être valides.</p>{last&&<button className="secondary" disabled={busy} onClick={()=>run(async()=>{const r=await request("/simulate",last);await refresh();setNotice(r.applied?"Événement appliqué":"Doublon ignoré : aucun nouvel envoi.")})}>Rejouer le dernier événement</button>}</article>}
 {tab==="Journal"&&<section className="grid"><article><h2>Événements</h2>{data.events.length?data.events.map(e=><div className="row" key={e.event_id}>{labels[e.kind]||"Annulation"} · {e.arrival}<p className="muted">{e.reservation_id}</p></div>):<p>Aucun événement simulé.</p>}<h2>Rappels</h2>{data.reminders.map((r,i)=><p key={i}>{r.due} · {r.status==="scheduled"?"Planifié (simulation)":"Annulé"}</p>)}</article><article><h2>Notifications</h2>{data.notifications.length?data.notifications.map((n,i)=><div className="row" key={i}><strong>{n.channel==="sms"?"SMS · Twilio":"Email · Brevo"}</strong><p>{n.text}</p><small>Simulation — non envoyé</small></div>):<p>Aucune notification.</p>}</article></section>}
 <footer>Cléora · Prototype de développement · Données fictives</footer></main></div>
}
